a=input('Enter a number:')
b=input('Enter another number:')
sum = int(a) + int(b)
print("The sum is:", sum)
sub = int(a) - int(b)
print("The difference is:", sub)
mult= int(a) * int(b)
print("The multiplication is:", mult)
div = int(a) / int(b)
print("The quotient is:", div)
print('The floor division is:', int(a) // int(b))
print("This is the first Python script in Chapter 1.")
print('The exponentiation is:', int(a) ** int(b))
print("This is the first Python script in Chapter 1.")