a=input('Enter a number:')
b=input('Enter another number:')
print("The sum is:", int(a) + int(b))
print('The sub is:', int(a) - int(b))
print('The mul is:', int(a) * int(b))
print('The div is:', int(a) / int(b))
print('The floor div is:', int(a) // int(b))
print('The mod is:', int(a) % int(b))
print('The exponent is:', int(a) ** int(b)) 
print("This is the first Python script in Chapter 1.")
