a = input("Enter Your Name: ")
print("My name is",a)

x=input("Enter first number: ")
y=input("Enter second number: ")
print(x+y)
print("Sum of", x, "and", y, "is", int(x) + int(y))
print("Multiplication of", x, "and", y, "is", int(x) * int(y))
print("Subtraction of", x, "and", y, "is", int(x) - int(y))
print("Division of", x, "and", y, "is", int(x) / int(y))
print("Modulus of", x, "and", y, "is", int(x) % int(y))
print("Exponentiation of", x, "and", y, "is", int(x) ** int(y))
print("Floor division of", x, "and", y, "is", int(x) // int(y))
print("Comparison of", x, "and", y, "is", int(x) == int(y))
print("Sum of", x, "and", y, "is", float(x) + float(y))